package tools

// Catalog returns all 150 Stockyard tools.
func Catalog() []Tool {
	return []Tool{
		{Slug: "mirage", Name: "Mirage", Tagline: "Self-hosted mock server", Port: 8590, Category: "developer", ProPrice: "$0.99"},
		{Slug: "barrage", Name: "Barrage", Tagline: "Self-hosted load tester", Port: 8600, Category: "developer", ProPrice: "$0.99"},
		{Slug: "strongbox", Name: "Strongbox", Tagline: "Self-hosted secret manager", Port: 8610, Category: "developer", ProPrice: "$1.99"},
		{Slug: "relay", Name: "Relay", Tagline: "Self-hosted webhook relay", Port: 8620, Category: "developer", ProPrice: "$0.99"},
		{Slug: "scout", Name: "Scout", Tagline: "Self-hosted dependency scanner", Port: 8630, Category: "developer", ProPrice: "$0.99"},
		{Slug: "tally", Name: "Tally", Tagline: "Self-hosted counter and gauge API", Port: 8640, Category: "developer", ProPrice: "$0.99"},
		{Slug: "codex", Name: "Codex", Tagline: "Self-hosted code snippet manager", Port: 8650, Category: "developer", ProPrice: "$0.99"},
		{Slug: "drifter", Name: "Drifter", Tagline: "Self-hosted database browser", Port: 8660, Category: "developer", ProPrice: "$0.99"},
		{Slug: "parcel", Name: "Parcel", Tagline: "Self-hosted package registry proxy", Port: 8670, Category: "developer", ProPrice: "$0.99"},
		{Slug: "sentinel", Name: "Sentinel", Tagline: "Self-hosted alert manager", Port: 8680, Category: "operations", ProPrice: "$0.99"},
		{Slug: "headcount", Name: "Headcount", Tagline: "Self-hosted user analytics", Port: 8690, Category: "operations", ProPrice: "$1.99"},
		{Slug: "roundup", Name: "Roundup", Tagline: "Self-hosted task manager", Port: 8700, Category: "operations", ProPrice: "$0.99"},
		{Slug: "brander", Name: "Brander", Tagline: "Self-hosted brand asset manager", Port: 8710, Category: "creator", ProPrice: "$0.99"},
		{Slug: "drover", Name: "Drover", Tagline: "Self-hosted background job queue", Port: 8720, Category: "developer", ProPrice: "$1.99"},
		{Slug: "pasture", Name: "Pasture", Tagline: "Self-hosted content scheduler", Port: 8730, Category: "creator", ProPrice: "$0.99"},
		{Slug: "outpost", Name: "Outpost", Tagline: "Self-hosted remote server monitor", Port: 8740, Category: "operations", ProPrice: "$0.99"},
		{Slug: "mailbag", Name: "Mailbag", Tagline: "Self-hosted email archive", Port: 8750, Category: "operations", ProPrice: "$0.99"},
		{Slug: "watcher", Name: "Watcher", Tagline: "Self-hosted file change monitor", Port: 8760, Category: "developer", ProPrice: "$0.99"},
		{Slug: "chronicle", Name: "Chronicle", Tagline: "Self-hosted event log", Port: 8770, Category: "operations", ProPrice: "$0.99"},
		{Slug: "crossroads", Name: "Crossroads", Tagline: "Self-hosted URL shortener", Port: 8780, Category: "creator", ProPrice: "$0.99"},
		{Slug: "saloon", Name: "Saloon", Tagline: "Self-hosted team chat", Port: 8790, Category: "operations", ProPrice: "$2.99"},
		{Slug: "grubstake", Name: "Grubstake", Tagline: "Self-hosted crowdfunding and pre-orders", Port: 8800, Category: "finance", ProPrice: "$0.99"},
		{Slug: "cutoff", Name: "Cutoff", Tagline: "Self-hosted API rate limiter", Port: 8810, Category: "developer", ProPrice: "$0.99"},
		{Slug: "prairie", Name: "Prairie", Tagline: "Self-hosted kanban project board", Port: 8820, Category: "operations", ProPrice: "$0.99"},
		{Slug: "almanac", Name: "Almanac", Tagline: "Self-hosted personal journal", Port: 8830, Category: "personal", ProPrice: "$0.99"},
		{Slug: "brandingiron", Name: "Branding Iron", Tagline: "Self-hosted release notes manager", Port: 8840, Category: "creator", ProPrice: "$0.99"},
		{Slug: "campfire", Name: "Campfire", Tagline: "Self-hosted async team standup tool", Port: 8850, Category: "operations", ProPrice: "$0.99"},
		{Slug: "chalkboard", Name: "Chalkboard", Tagline: "Self-hosted collaborative whiteboard", Port: 8860, Category: "creator", ProPrice: "$0.99"},
		{Slug: "cipher", Name: "Cipher", Tagline: "Self-hosted password manager", Port: 8870, Category: "personal", ProPrice: "$0.99"},
		{Slug: "homestead", Name: "Homestead", Tagline: "Self-hosted server inventory and monitor", Port: 8880, Category: "operations", ProPrice: "$0.99"},
		{Slug: "lasso", Name: "Lasso", Tagline: "Self-hosted link shortener", Port: 8890, Category: "developer", ProPrice: "$0.99"},
		{Slug: "ledger", Name: "Ledger", Tagline: "Self-hosted double-entry bookkeeping", Port: 8900, Category: "finance", ProPrice: "$2.99"},
		{Slug: "muster", Name: "Muster", Tagline: "Self-hosted deployment tracker", Port: 8910, Category: "operations", ProPrice: "$0.99"},
		{Slug: "paddock", Name: "Paddock", Tagline: "Self-hosted public status page", Port: 8920, Category: "operations", ProPrice: "$0.99"},
		{Slug: "ponyexpress", Name: "Pony Express", Tagline: "Self-hosted transactional email sender", Port: 8930, Category: "creator", ProPrice: "$0.99"},
		{Slug: "post", Name: "Post", Tagline: "Self-hosted blog engine", Port: 8940, Category: "creator", ProPrice: "$0.99"},
		{Slug: "pulpit", Name: "Pulpit", Tagline: "Self-hosted presentation tool", Port: 8950, Category: "creator", ProPrice: "$0.99"},
		{Slug: "rangeland", Name: "Rangeland", Tagline: "Self-hosted multi-tenant workspace manager", Port: 8960, Category: "developer", ProPrice: "$2.99"},
		{Slug: "roster", Name: "Roster", Tagline: "Self-hosted team directory", Port: 8970, Category: "operations", ProPrice: "$0.99"},
		{Slug: "rustler", Name: "Rustler", Tagline: "Self-hosted web scraper and data collector", Port: 8980, Category: "developer", ProPrice: "$0.99"},
		{Slug: "saddlebag", Name: "Saddlebag", Tagline: "Self-hosted file manager", Port: 8990, Category: "operations", ProPrice: "$0.99"},
		{Slug: "saltlick", Name: "Salt Lick", Tagline: "Self-hosted feature flag service", Port: 9000, Category: "creator", ProPrice: "$0.99"},
		{Slug: "spur", Name: "Spur", Tagline: "Self-hosted task runner and automation", Port: 9010, Category: "developer", ProPrice: "$0.99"},
		{Slug: "stampede", Name: "Stampede", Tagline: "Self-hosted load balancer and traffic router", Port: 9020, Category: "developer", ProPrice: "$0.99"},
		{Slug: "telegraph", Name: "Telegraph", Tagline: "Self-hosted notification hub", Port: 9030, Category: "operations", ProPrice: "$0.99"},
		{Slug: "ticker", Name: "Ticker", Tagline: "Self-hosted metrics and time series dashboard", Port: 9040, Category: "developer", ProPrice: "$0.99"},
		{Slug: "wateringhole", Name: "Watering Hole", Tagline: "Self-hosted community forum", Port: 9050, Category: "creator", ProPrice: "$2.99"},
		{Slug: "wrangler", Name: "Wrangler", Tagline: "Self-hosted ETL and data pipeline runner", Port: 9060, Category: "developer", ProPrice: "$1.99"},
		{Slug: "billfold", Name: "Billfold", Tagline: "Self-hosted invoice generator", Port: 9070, Category: "finance", ProPrice: "$0.99"},
		{Slug: "dossier", Name: "Dossier", Tagline: "Self-hosted contact and CRM manager", Port: 9080, Category: "finance", ProPrice: "$0.99"},
		{Slug: "probe", Name: "Probe", Tagline: "Self-hosted HTTP request inspector", Port: 9090, Category: "developer", ProPrice: "$0.99"},
		{Slug: "quarry", Name: "Quarry", Tagline: "Self-hosted log aggregator and search", Port: 9100, Category: "operations", ProPrice: "$0.99"},
		{Slug: "hub", Name: "Hub", Tagline: "Self-hosted request relay and inspector", Port: 9110, Category: "developer", ProPrice: "$0.99"},
		{Slug: "scaffold", Name: "Scaffold", Tagline: "Self-hosted project scaffolding server", Port: 9120, Category: "developer", ProPrice: "$0.99"},
		{Slug: "assay", Name: "Assay", Tagline: "Self-hosted API testing suite", Port: 9130, Category: "developer", ProPrice: "$0.99"},
		{Slug: "pipeline", Name: "Pipeline", Tagline: "Self-hosted data pipeline orchestrator", Port: 9140, Category: "developer", ProPrice: "$1.99"},
		{Slug: "embargo", Name: "Embargo", Tagline: "Self-hosted feature flag manager", Port: 9150, Category: "developer", ProPrice: "$0.99"},
		{Slug: "manifest", Name: "Manifest", Tagline: "Self-hosted dependency manifest tracker", Port: 9160, Category: "developer", ProPrice: "$0.99"},
		{Slug: "switchboard", Name: "Switchboard", Tagline: "Self-hosted service registry and discovery", Port: 9170, Category: "developer", ProPrice: "$0.99"},
		{Slug: "bellwether", Name: "Bellwether", Tagline: "Self-hosted uptime and health monitor", Port: 9180, Category: "operations", ProPrice: "$0.99"},
		{Slug: "granary", Name: "Granary", Tagline: "Self-hosted object and file storage", Port: 9190, Category: "developer", ProPrice: "$0.99"},
		{Slug: "books", Name: "Books", Tagline: "Self-hosted business bookkeeping", Port: 9200, Category: "finance", ProPrice: "$1.99"},
		{Slug: "presskit", Name: "Presskit", Tagline: "Self-hosted press kit and media page", Port: 9210, Category: "creator", ProPrice: "$0.99"},
		{Slug: "registry", Name: "Registry", Tagline: "Self-hosted container and package registry", Port: 9220, Category: "developer", ProPrice: "$1.99"},
		{Slug: "cartograph", Name: "Cartograph", Tagline: "Self-hosted sitemap generator and crawler", Port: 9230, Category: "creator", ProPrice: "$0.99"},
		{Slug: "typeset", Name: "Typeset", Tagline: "Self-hosted documentation generator", Port: 9240, Category: "creator", ProPrice: "$0.99"},
		{Slug: "archive", Name: "Archive", Tagline: "Self-hosted content archive and clipping service", Port: 9250, Category: "personal", ProPrice: "$0.99"},
		{Slug: "glossary", Name: "Glossary", Tagline: "Self-hosted term and jargon manager", Port: 9260, Category: "creator", ProPrice: "$0.99"},
		{Slug: "scribe", Name: "Scribe", Tagline: "Self-hosted transcription and note taker", Port: 9270, Category: "creator", ProPrice: "$0.99"},
		{Slug: "cartridge", Name: "Cartridge", Tagline: "Self-hosted config and settings manager", Port: 9280, Category: "developer", ProPrice: "$0.99"},
		{Slug: "surveyor", Name: "Surveyor", Tagline: "Self-hosted form builder and survey tool", Port: 9290, Category: "creator", ProPrice: "$0.99"},
		{Slug: "covenant", Name: "Covenant", Tagline: "Self-hosted policy and compliance manager", Port: 9300, Category: "operations", ProPrice: "$0.99"},
		{Slug: "deposition", Name: "Deposition", Tagline: "Self-hosted tamper-evident audit log", Port: 9310, Category: "operations", ProPrice: "$0.99"},
		{Slug: "bounty", Name: "Bounty", Tagline: "Self-hosted bug tracker and issue manager", Port: 9320, Category: "developer", ProPrice: "$0.99"},
		{Slug: "escrow", Name: "Escrow", Tagline: "Self-hosted approval workflow engine", Port: 9330, Category: "operations", ProPrice: "$0.99"},
		{Slug: "inquest", Name: "Inquest", Tagline: "Self-hosted incident manager", Port: 9340, Category: "operations", ProPrice: "$0.99"},
		{Slug: "handbook", Name: "Handbook", Tagline: "Self-hosted internal wiki and knowledge base", Port: 9350, Category: "operations", ProPrice: "$0.99"},
		{Slug: "deed", Name: "Deed", Tagline: "Self-hosted digital asset and license registry", Port: 9360, Category: "finance", ProPrice: "$0.99"},
		{Slug: "notebook", Name: "Notebook", Tagline: "Self-hosted personal note-taking app", Port: 9370, Category: "personal", ProPrice: "$0.99"},
		{Slug: "trailhead", Name: "Trailhead", Tagline: "Self-hosted habit and goal tracker", Port: 9380, Category: "personal", ProPrice: "$0.99"},
		{Slug: "crucible", Name: "Crucible", Tagline: "Self-hosted A/B testing engine", Port: 9650, Category: "developer", ProPrice: "$0.99"},
		{Slug: "viaduct", Name: "Viaduct", Tagline: "Self-hosted API version router", Port: 9660, Category: "developer", ProPrice: "$0.99"},
		{Slug: "tinderbox", Name: "Tinderbox", Tagline: "Self-hosted CI/CD trigger server", Port: 9670, Category: "developer", ProPrice: "$0.99"},
		{Slug: "seismograph", Name: "Seismograph", Tagline: "Self-hosted error tracker", Port: 9680, Category: "developer", ProPrice: "$0.99"},
		{Slug: "conduit", Name: "Conduit", Tagline: "Self-hosted data sync engine", Port: 9690, Category: "developer", ProPrice: "$0.99"},
		{Slug: "parcelproxy", Name: "Parcel Proxy", Tagline: "Self-hosted package registry proxy", Port: 9700, Category: "developer", ProPrice: "$0.99"},
		{Slug: "githost", Name: "Githost", Tagline: "Self-hosted Git repository host", Port: 9710, Category: "developer", ProPrice: "$1.99"},
		{Slug: "ordnance", Name: "Ordnance", Tagline: "Self-hosted vulnerability scanner", Port: 9720, Category: "developer", ProPrice: "$0.99"},
		{Slug: "metrics", Name: "Metrics", Tagline: "Self-hosted real-time metrics dashboard", Port: 9730, Category: "developer", ProPrice: "$0.99"},
		{Slug: "pathfinder", Name: "Pathfinder", Tagline: "Self-hosted URL routing and proxy rules manager", Port: 9740, Category: "developer", ProPrice: "$0.99"},
		{Slug: "announcements", Name: "Announcements", Tagline: "Self-hosted internal announcement board", Port: 9750, Category: "operations", ProPrice: "$0.99"},
		{Slug: "notify", Name: "Notify", Tagline: "Self-hosted SMS and notification sender", Port: 9760, Category: "operations", ProPrice: "$0.99"},
		{Slug: "courier", Name: "Courier", Tagline: "Self-hosted internal message queue", Port: 9770, Category: "operations", ProPrice: "$0.99"},
		{Slug: "megaphone", Name: "Megaphone", Tagline: "Self-hosted status page with notifications", Port: 9780, Category: "operations", ProPrice: "$0.99"},
		{Slug: "parlor", Name: "Parlor", Tagline: "Self-hosted live chat widget", Port: 9790, Category: "creator", ProPrice: "$0.99"},
		{Slug: "grapevine", Name: "Grapevine", Tagline: "Self-hosted knowledge base and FAQ", Port: 9800, Category: "operations", ProPrice: "$0.99"},
		{Slug: "semaphore", Name: "Semaphore", Tagline: "Self-hosted team availability board", Port: 9810, Category: "operations", ProPrice: "$0.99"},
		{Slug: "podium", Name: "Podium", Tagline: "Self-hosted product feedback tool", Port: 9820, Category: "creator", ProPrice: "$0.99"},
		{Slug: "assayer", Name: "Assayer", Tagline: "Self-hosted revenue and subscription tracker", Port: 9830, Category: "finance", ProPrice: "$0.99"},
		{Slug: "steward", Name: "Steward", Tagline: "Self-hosted expense tracker", Port: 9840, Category: "finance", ProPrice: "$0.99"},
		{Slug: "consortium", Name: "Consortium", Tagline: "Self-hosted vendor and supplier tracker", Port: 9850, Category: "finance", ProPrice: "$0.99"},
		{Slug: "exchequer", Name: "Exchequer", Tagline: "Self-hosted budget tracker", Port: 9860, Category: "finance", ProPrice: "$0.99"},
		{Slug: "dividend", Name: "Dividend", Tagline: "Self-hosted affiliate program manager", Port: 9870, Category: "finance", ProPrice: "$0.99"},
		{Slug: "prospector", Name: "Prospector", Tagline: "Self-hosted sales pipeline tracker", Port: 9880, Category: "finance", ProPrice: "$0.99"},
		{Slug: "sundial", Name: "Sundial", Tagline: "Self-hosted time tracker", Port: 9890, Category: "personal", ProPrice: "$0.99"},
		{Slug: "decisionlog", Name: "Decisionlog", Tagline: "Self-hosted decision log", Port: 9900, Category: "personal", ProPrice: "$0.99"},
		{Slug: "quiver", Name: "Quiver", Tagline: "Self-hosted reading list and learning tracker", Port: 9910, Category: "personal", ProPrice: "$0.99"},
		{Slug: "feedreader", Name: "Feedreader", Tagline: "Self-hosted RSS and news aggregator", Port: 9920, Category: "personal", ProPrice: "$0.99"},
		{Slug: "waystation", Name: "Waystation", Tagline: "Self-hosted travel and trip planner", Port: 9930, Category: "personal", ProPrice: "$0.99"},
		{Slug: "curator", Name: "Curator", Tagline: "Self-hosted recipe and meal planner", Port: 9940, Category: "personal", ProPrice: "$0.99"},
		{Slug: "mainspring", Name: "Mainspring", Tagline: "Self-hosted cron job scheduler", Port: 9950, Category: "developer", ProPrice: "$0.99"},
		{Slug: "crucible2", Name: "Crucible II", Tagline: "Self-hosted code review checklist manager", Port: 9960, Category: "developer", ProPrice: "$0.99"},
		{Slug: "switchman", Name: "Switchman", Tagline: "Self-hosted blue-green deploy manager", Port: 9970, Category: "developer", ProPrice: "$0.99"},
		{Slug: "assay2", Name: "Assay II", Tagline: "Self-hosted API contract tester", Port: 9980, Category: "developer", ProPrice: "$0.99"},
		{Slug: "bandolier", Name: "Bandolier", Tagline: "Self-hosted environment variable manager", Port: 9990, Category: "developer", ProPrice: "$0.99"},
		{Slug: "ironworks", Name: "Ironworks", Tagline: "Self-hosted build artifact storage", Port: 10000, Category: "developer", ProPrice: "$0.99"},
		{Slug: "plumb", Name: "Plumb", Tagline: "Self-hosted database migration tracker", Port: 10010, Category: "developer", ProPrice: "$0.99"},
		{Slug: "signalman", Name: "Signalman", Tagline: "Self-hosted alerting rules engine", Port: 10020, Category: "operations", ProPrice: "$0.99"},
		{Slug: "rampart", Name: "Rampart", Tagline: "Self-hosted IP blocklist manager", Port: 10030, Category: "developer", ProPrice: "$0.99"},
		{Slug: "smelter", Name: "Smelter", Tagline: "Self-hosted data transformation API", Port: 10040, Category: "developer", ProPrice: "$0.99"},
		{Slug: "bellringer", Name: "Bellringer", Tagline: "Self-hosted web push notification server", Port: 10050, Category: "developer", ProPrice: "$0.99"},
		{Slug: "broadside", Name: "Broadside", Tagline: "Self-hosted press release tracker", Port: 10060, Category: "creator", ProPrice: "$0.99"},
		{Slug: "agora", Name: "Agora", Tagline: "Self-hosted voting and polling tool", Port: 10070, Category: "creator", ProPrice: "$0.99"},
		{Slug: "hearthside", Name: "Hearthside", Tagline: "Self-hosted sprint retrospective tool", Port: 10080, Category: "operations", ProPrice: "$0.99"},
		{Slug: "pennant", Name: "Pennant", Tagline: "Self-hosted loyalty and points system", Port: 10090, Category: "finance", ProPrice: "$0.99"},
		{Slug: "soapbox", Name: "Soapbox", Tagline: "Self-hosted internal Q&amp;A and Stack Overflow", Port: 10100, Category: "operations", ProPrice: "$0.99"},
		{Slug: "gazette2", Name: "Gazette II", Tagline: "Self-hosted internal blog and news feed", Port: 10110, Category: "operations", ProPrice: "$0.99"},
		{Slug: "concierge", Name: "Concierge", Tagline: "Self-hosted customer onboarding checklists", Port: 10120, Category: "creator", ProPrice: "$0.99"},
		{Slug: "surveyor2", Name: "Surveyor II", Tagline: "Self-hosted NPS and satisfaction tracker", Port: 10130, Category: "creator", ProPrice: "$0.99"},
		{Slug: "almanac3", Name: "Almanac III", Tagline: "Self-hosted data dictionary and schema registry", Port: 10140, Category: "developer", ProPrice: "$0.99"},
		{Slug: "cartwright", Name: "Cartwright", Tagline: "Self-hosted dashboard and report builder", Port: 10150, Category: "developer", ProPrice: "$0.99"},
		{Slug: "prospector2", Name: "Prospector II", Tagline: "Self-hosted lead scoring engine", Port: 10160, Category: "finance", ProPrice: "$0.99"},
		{Slug: "dowser", Name: "Dowser", Tagline: "Self-hosted data quality monitor", Port: 10170, Category: "developer", ProPrice: "$0.99"},
		{Slug: "windmill", Name: "Windmill", Tagline: "Self-hosted data pipeline visualizer", Port: 10180, Category: "developer", ProPrice: "$0.99"},
		{Slug: "archivist", Name: "Archivist", Tagline: "Self-hosted personal document manager", Port: 10190, Category: "personal", ProPrice: "$0.99"},
		{Slug: "apothecary", Name: "Apothecary", Tagline: "Self-hosted health and medication tracker", Port: 10200, Category: "personal", ProPrice: "$0.99"},
		{Slug: "paddock2", Name: "Paddock II", Tagline: "Self-hosted plant and garden tracker", Port: 10210, Category: "personal", ProPrice: "$0.99"},
		{Slug: "cellar", Name: "Cellar", Tagline: "Self-hosted wine and spirits inventory", Port: 10220, Category: "personal", ProPrice: "$0.99"},
		{Slug: "quartermaster", Name: "Quartermaster", Tagline: "Self-hosted home inventory manager", Port: 10230, Category: "personal", ProPrice: "$0.99"},
		{Slug: "meridian", Name: "Meridian", Tagline: "Self-hosted life dashboard", Port: 10240, Category: "personal", ProPrice: "$0.99"},
		{Slug: "corral", Name: "Corral", Tagline: "Self-hosted webhook inbox", Port: 8760, Category: "developer", ProPrice: "$0.99"},
		{Slug: "gate", Name: "Gate", Tagline: "Self-hosted reverse proxy and auth gateway", Port: 8650, Category: "developer", ProPrice: "$2.99"},
		{Slug: "trough", Name: "Trough", Tagline: "Self-hosted LLM API cost monitor", Port: 8670, Category: "developer", ProPrice: "$2.99"},
		{Slug: "fence", Name: "Fence", Tagline: "Self-hosted API key vault", Port: 8640, Category: "developer", ProPrice: "$4.99"},
		{Slug: "brand", Name: "Brand", Tagline: "Self-hosted audit trail and compliance log", Port: 8630, Category: "operations", ProPrice: "$4.99"},
		{Slug: "dispatch", Name: "Dispatch", Tagline: "Self-hosted task dispatch and routing", Port: 8560, Category: "developer", ProPrice: "$0.99"},
		{Slug: "billfold2", Name: "Billfold II", Tagline: "Self-hosted contractor timesheet and billing", Port: 8570, Category: "finance", ProPrice: "$0.99"},
		{Slug: "outfitter", Name: "Outfitter", Tagline: "Self-hosted employee onboarding manager", Port: 8580, Category: "operations", ProPrice: "$0.99"},
		{Slug: "silo", Name: "Silo", Tagline: "Self-hosted data isolation and partitioning layer", Port: 8545, Category: "developer", ProPrice: "$1.99"},
		{Slug: "ledger2", Name: "Ledger II", Tagline: "Self-hosted personal finance tracker", Port: 8555, Category: "finance", ProPrice: "$0.99"},
	}
}
