package tools

// Catalog returns all 150 Stockyard tools.
func Catalog() []Tool {
	return []Tool{
		{Slug: "agora", Name: "Agora", Tagline: "Create polls, share a link, collect votes, see results. No Typeform, no SurveyMo", Port: 1007, Category: "creator", ProPrice: "$0.99"},
		{Slug: "almanac", Name: "Almanac", Tagline: "Write daily entries, tag them, search them, review past entries on this day. No ", Port: 8830, Category: "personal", ProPrice: "$0.99"},
		{Slug: "almanac3", Name: "Almanac III", Tagline: "Document every database table, column, and relationship. The thing data teams bu", Port: 1014, Category: "developer", ProPrice: "$0.99"},
		{Slug: "announcements", Name: "Announcements", Tagline: "Post company-wide announcements, team updates, and policy changes. Everyone sees", Port: 9750, Category: "operations", ProPrice: "$0.99"},
		{Slug: "apothecary", Name: "Apothecary", Tagline: "Log medications, symptoms, measurements, appointments. Your health data on your ", Port: 1020, Category: "personal", ProPrice: "$0.99"},
		{Slug: "archive", Name: "Archive", Tagline: "Save web pages, PDFs, and articles for permanent offline access. Full-text searc", Port: 9250, Category: "personal", ProPrice: "$0.99"},
		{Slug: "archivist", Name: "Archivist", Tagline: "Upload PDFs, images, and text files, tag them, search the contents. Your own Dro", Port: 1019, Category: "personal", ProPrice: "$0.99"},
		{Slug: "assay", Name: "Assay", Tagline: "Define API test cases with expected status codes, headers, and body assertions. ", Port: 9130, Category: "developer", ProPrice: "$0.99"},
		{Slug: "assay2", Name: "Assay II", Tagline: "Define expected request and response shapes, run them against your API on a sche", Port: 9980, Category: "developer", ProPrice: "$0.99"},
		{Slug: "assayer", Name: "Assayer", Tagline: "Log your MRR, track churn, visualize growth, forecast runway. For bootstrapped f", Port: 9830, Category: "finance", ProPrice: "$0.99"},
		{Slug: "bandolier", Name: "Bandolier", Tagline: "Store env vars per environment, track changes over time, see who changed what an", Port: 9990, Category: "developer", ProPrice: "$0.99"},
		{Slug: "barrage", Name: "Barrage", Tagline: "Define load test scenarios, ramp up concurrent users, see p50/p95/p99 latency in", Port: 8600, Category: "developer", ProPrice: "$0.99"},
		{Slug: "bellringer", Name: "Bellringer", Tagline: "Send web push notifications to your users without Firebase. VAPID keys, subscrip", Port: 1005, Category: "developer", ProPrice: "$0.99"},
		{Slug: "bellwether", Name: "Bellwether", Tagline: "Check URLs, TCP ports, and DNS records on a schedule. Get alerted when they fail", Port: 9180, Category: "operations", ProPrice: "$0.99"},
		{Slug: "billfold", Name: "Billfold", Tagline: "Create invoices, send them by email, track payment status, generate PDF receipts", Port: 9070, Category: "finance", ProPrice: "$0.99"},
		{Slug: "billfold2", Name: "Billfold II", Tagline: "Track billable hours by client, generate invoices automatically, send payment re", Port: 0, Category: "developer", ProPrice: "$0.99"},
		{Slug: "books", Name: "Books", Tagline: "Record transactions, categorize them, reconcile accounts, generate monthly repor", Port: 9200, Category: "finance", ProPrice: "$0.99"},
		{Slug: "bounty", Name: "Bounty", Tagline: "Create issues, triage them, assign them, track resolution. GitHub Issues but on ", Port: 9320, Category: "developer", ProPrice: "$0.99"},
		{Slug: "brand", Name: "Brand", Tagline: "SHA-256 hash-chained audit log with chain verification and evidence export. 10,0", Port: 9999, Category: "operations", ProPrice: "$0.99"},
		{Slug: "brander", Name: "Brander", Tagline: "Upload logos, color palettes, fonts, and brand guidelines. Share a link to the r", Port: 8710, Category: "creator", ProPrice: "$0.99"},
		{Slug: "brandingiron", Name: "Branding Iron", Tagline: "Write release notes, publish them to a changelog page, notify subscribers by ema", Port: 8840, Category: "creator", ProPrice: "$0.99"},
		{Slug: "broadside", Name: "Broadside", Tagline: "Write your release, log which journalists you contacted, track responses, manage", Port: 1006, Category: "creator", ProPrice: "$0.99"},
		{Slug: "campfire", Name: "Campfire", Tagline: "Post your daily standup, see what your team is working on, no meeting required. ", Port: 8850, Category: "operations", ProPrice: "$0.99"},
		{Slug: "cartograph", Name: "Cartograph", Tagline: "Crawl your site, generate a sitemap.xml, audit for broken links, track page coun", Port: 9230, Category: "creator", ProPrice: "$0.99"},
		{Slug: "cartridge", Name: "Cartridge", Tagline: "Store application config in a central UI instead of scattered env files. Version", Port: 9280, Category: "developer", ProPrice: "$0.99"},
		{Slug: "cartwright", Name: "Cartwright", Tagline: "Connect to any SQLite database, drag and drop charts, share dashboards. Metabase", Port: 1015, Category: "developer", ProPrice: "$0.99"},
		{Slug: "cellar", Name: "Cellar", Tagline: "Log bottles, vintages, tasting notes, valuations. Vivino is a social network. Th", Port: 1022, Category: "personal", ProPrice: "$0.99"},
		{Slug: "chalkboard", Name: "Chalkboard", Tagline: "Draw, add sticky notes, collaborate in real time over WebSocket. Miro for teams ", Port: 8860, Category: "creator", ProPrice: "$0.99"},
		{Slug: "chronicle", Name: "Chronicle", Tagline: "POST structured events from any service, search and filter them, build simple da", Port: 8770, Category: "operations", ProPrice: "$0.99"},
		{Slug: "cipher", Name: "Cipher", Tagline: "Store credentials encrypted with AES-256, share vaults with teammates, access fr", Port: 8870, Category: "personal", ProPrice: "$0.99"},
		{Slug: "codex", Name: "Codex", Tagline: "Save code snippets with tags, search instantly, share links to teammates. The pr", Port: 8650, Category: "developer", ProPrice: "$0.99"},
		{Slug: "concierge", Name: "Concierge", Tagline: "Define onboarding steps per product tier, embed them in your app via script tag,", Port: 1012, Category: "creator", ProPrice: "$0.99"},
		{Slug: "conduit", Name: "Conduit", Tagline: "Define a source, define a destination, define a schedule. Syncs data between any", Port: 9690, Category: "developer", ProPrice: "$0.99"},
		{Slug: "consortium", Name: "Consortium", Tagline: "Track every vendor relationship — contacts, contracts, SLAs, renewal dates, perf", Port: 9850, Category: "finance", ProPrice: "$0.99"},
		{Slug: "corral", Name: "Corral", Tagline: "Capture, inspect, replay, and forward webhooks. 3 endpoints free. Pro at $0.99/m", Port: 9999, Category: "developer", ProPrice: "$0.99"},
		{Slug: "courier", Name: "Courier", Tagline: "Post tasks and messages between team members, track completion, no email thread.", Port: 9770, Category: "operations", ProPrice: "$0.99"},
		{Slug: "covenant", Name: "Covenant", Tagline: "Write policies, version them, require team acknowledgment, track who's read wha", Port: 9300, Category: "operations", ProPrice: "$0.99"},
		{Slug: "crossroads", Name: "Crossroads", Tagline: "Create short links, track clicks by location and referrer, set expiry dates, pro", Port: 8780, Category: "creator", ProPrice: "$0.99"},
		{Slug: "crucible", Name: "Crucible", Tagline: "Define experiments, split traffic, collect results, calculate statistical signif", Port: 9650, Category: "developer", ProPrice: "$0.99"},
		{Slug: "crucible2", Name: "Crucible II", Tagline: "Define review standards per language or project, attach them to PRs via webhook,", Port: 9960, Category: "developer", ProPrice: "$0.99"},
		{Slug: "curator", Name: "Curator", Tagline: "Save recipes, plan a week of meals, generate a shopping list. The tool everyone ", Port: 9940, Category: "personal", ProPrice: "$0.99"},
		{Slug: "cutoff", Name: "Cutoff", Tagline: "Define rate limit rules per API key, IP, or user. Apply them in front of any HTT", Port: 8810, Category: "developer", ProPrice: "$0.99"},
		{Slug: "decisionlog", Name: "Decisionlog", Tagline: "Record important decisions, the context, the reasoning, and the outcome. Search ", Port: 9900, Category: "personal", ProPrice: "$0.99"},
		{Slug: "deed", Name: "Deed", Tagline: "Log every software license, hardware asset, and domain you own. Track expiry dat", Port: 9360, Category: "finance", ProPrice: "$0.99"},
		{Slug: "deposition", Name: "Deposition", Tagline: "Write audit records that can't be modified. Sign them with a key, verify the ch", Port: 9310, Category: "operations", ProPrice: "$0.99"},
		{Slug: "dispatch", Name: "Dispatch", Tagline: "Route incoming tasks and requests to the right worker or queue based on rules. T", Port: 8560, Category: "developer", ProPrice: "$0.99"},
		{Slug: "dividend", Name: "Dividend", Tagline: "Create referral codes, track signups, calculate commissions, export payout repor", Port: 9870, Category: "finance", ProPrice: "$0.99"},
		{Slug: "dossier", Name: "Dossier", Tagline: "Store contacts, log interactions, set follow-up reminders, track deal history. H", Port: 9080, Category: "finance", ProPrice: "$0.99"},
		{Slug: "dowser", Name: "Dowser", Tagline: "Define expectations for your data — no nulls in this column, values in this rang", Port: 1017, Category: "developer", ProPrice: "$0.99"},
		{Slug: "drifter", Name: "Drifter", Tagline: "Connect to any SQLite database, browse tables, run queries, inspect schema. The ", Port: 8660, Category: "developer", ProPrice: "$0.99"},
		{Slug: "drover", Name: "Drover", Tagline: "Enqueue jobs, process with workers, retry failures. Sidekiq without Ruby, BullMQ", Port: 1001, Category: "developer", ProPrice: "$0.99"},
		{Slug: "embargo", Name: "Embargo", Tagline: "Toggle features per user, percentage rollout, or environment. No LaunchDarkly SD", Port: 9150, Category: "developer", ProPrice: "$0.99"},
		{Slug: "escrow", Name: "Escrow", Tagline: "Define multi-step approval workflows for any request — code deploys, budget spen", Port: 9330, Category: "operations", ProPrice: "$0.99"},
		{Slug: "exchequer", Name: "Exchequer", Tagline: "Define budgets per department or project, log actuals, forecast end-of-period. T", Port: 9860, Category: "finance", ProPrice: "$0.99"},
		{Slug: "feedreader", Name: "Feedreader", Tagline: "Subscribe to RSS feeds, newsletters via email forwarding, and keyword alerts. Yo", Port: 9920, Category: "personal", ProPrice: "$0.99"},
		{Slug: "fence", Name: "Fence", Tagline: "Encrypted team vault for API credentials. Issue scoped tokens, log every access,", Port: 9999, Category: "developer", ProPrice: "$0.99"},
		{Slug: "gate", Name: "Gate", Tagline: "Reverse proxy with API key auth, session login, rate limiting, and access logs. ", Port: 9999, Category: "developer", ProPrice: "$0.99"},
		{Slug: "gazette2", Name: "Gazette II", Tagline: "Leaders post updates, employees read them, reactions and comments. Replaces the ", Port: 1011, Category: "operations", ProPrice: "$0.99"},
		{Slug: "githost", Name: "Githost", Tagline: "Create repos, manage access, review PRs, track issues. Not GitLab (heavy), not G", Port: 9710, Category: "developer", ProPrice: "$0.99"},
		{Slug: "glossary", Name: "Glossary", Tagline: "Define your company's terminology, link related terms, publish a searchable glo", Port: 9260, Category: "creator", ProPrice: "$0.99"},
		{Slug: "granary", Name: "Granary", Tagline: "Upload files, get back a URL. S3-compatible API so your existing tooling works. ", Port: 9190, Category: "developer", ProPrice: "$0.99"},
		{Slug: "grapevine", Name: "Grapevine", Tagline: "Write answers to common questions, publish them internally, track which ones get", Port: 9800, Category: "operations", ProPrice: "$0.99"},
		{Slug: "grubstake", Name: "Grubstake", Tagline: "Create a campaign, accept pre-orders via Stripe, track backers and goals. The Ki", Port: 8800, Category: "finance", ProPrice: "$0.99"},
		{Slug: "handbook", Name: "Handbook", Tagline: "Write docs, organize them into spaces, search them. Notion for teams who want th", Port: 9350, Category: "operations", ProPrice: "$0.99"},
		{Slug: "headcount", Name: "Headcount", Tagline: "Track signups, logins, active users, and funnels. No cookie banners, no GDPR nig", Port: 8690, Category: "operations", ProPrice: "$0.99"},
		{Slug: "hearthside", Name: "Hearthside", Tagline: "Run sprint retros, collect good/bad/improve items anonymously, vote on prioritie", Port: 1008, Category: "operations", ProPrice: "$0.99"},
		{Slug: "homestead", Name: "Homestead", Tagline: "Track every server you run — hostname, OS, IP, installed services — and monitor ", Port: 8880, Category: "operations", ProPrice: "$0.99"},
		{Slug: "hub", Name: "Hub", Tagline: "Install, start, stop, and monitor all 150 Stockyard tools from a single dashboar", Port: 1001, Category: "developer", ProPrice: "$0.99"},
		{Slug: "inquest", Name: "Inquest", Tagline: "Declare incidents, assign responders, track timelines, write postmortems. Incide", Port: 9340, Category: "operations", ProPrice: "$0.99"},
		{Slug: "ironworks", Name: "Ironworks", Tagline: "Store compiled binaries, build outputs, and release artifacts. Download them by ", Port: 1000, Category: "developer", ProPrice: "$0.99"},
		{Slug: "lasso", Name: "Lasso", Tagline: "Shorten URLs, track clicks, manage redirects. Self-hosted Bitly alternative. Fre", Port: 9999, Category: "developer", ProPrice: "$0.99"},
		{Slug: "ledger", Name: "Ledger", Tagline: "Track income, expenses, assets, and liabilities with real double-entry accountin", Port: 8900, Category: "finance", ProPrice: "$0.99"},
		{Slug: "ledger2", Name: "Ledger II", Tagline: "Track income, expenses, net worth, and budgets. Link bank accounts via CSV impor", Port: 0, Category: "developer", ProPrice: "$0.99"},
		{Slug: "mailbag", Name: "Mailbag", Tagline: "Forward a copy of every email to Mailbag, search it instantly, never lose an imp", Port: 8750, Category: "operations", ProPrice: "$0.99"},
		{Slug: "mainspring", Name: "Mainspring", Tagline: "Define cron jobs, run them, see logs, get alerted on failures. No server crontab", Port: 9950, Category: "developer", ProPrice: "$0.99"},
		{Slug: "manifest", Name: "Manifest", Tagline: "Track every library, framework, and service your projects depend on. Know which ", Port: 9160, Category: "developer", ProPrice: "$0.99"},
		{Slug: "megaphone", Name: "Megaphone", Tagline: "Status page with subscriber notifications. Subscribers get email when status cha", Port: 9780, Category: "operations", ProPrice: "$0.99"},
		{Slug: "meridian", Name: "Meridian", Tagline: "Combine your Trailhead habits, Sundial time tracking, Quiver reading list, and p", Port: 1024, Category: "personal", ProPrice: "$0.99"},
		{Slug: "metrics", Name: "Metrics", Tagline: "Define counters and gauges via a simple HTTP API, visualize them in real time. S", Port: 9730, Category: "developer", ProPrice: "$0.99"},
		{Slug: "mirage", Name: "Mirage", Tagline: "Define mock HTTP endpoints with expected responses, test your app against them, ", Port: 8590, Category: "developer", ProPrice: "$0.99"},
		{Slug: "muster", Name: "Muster", Tagline: "Log every deployment — what was deployed, when, by whom, to which environment. S", Port: 8910, Category: "operations", ProPrice: "$0.99"},
		{Slug: "notebook", Name: "Notebook", Tagline: "Write notes in Markdown, organize them in notebooks, search instantly. Obsidian ", Port: 9370, Category: "personal", ProPrice: "$0.99"},
		{Slug: "notify", Name: "Notify", Tagline: "Define message templates, send to lists via your own Twilio account or SMTP. Man", Port: 9760, Category: "operations", ProPrice: "$0.99"},
		{Slug: "ordnance", Name: "Ordnance", Tagline: "Point it at a repo or a list of packages, it checks against known CVE databases,", Port: 9720, Category: "developer", ProPrice: "$0.99"},
		{Slug: "outfitter", Name: "Outfitter", Tagline: "Create onboarding checklists per role, assign them to new hires, track completio", Port: 0, Category: "developer", ProPrice: "$0.99"},
		{Slug: "outpost", Name: "Outpost", Tagline: "Check that your servers, APIs, and services are responding. Get alerted when the", Port: 8740, Category: "operations", ProPrice: "$0.99"},
		{Slug: "paddock", Name: "Paddock", Tagline: "Define your services, set their status, let users subscribe for incident notific", Port: 9999, Category: "operations", ProPrice: "$0.99"},
		{Slug: "paddock2", Name: "Paddock II", Tagline: "Log your plants, watering schedules, growth notes, harvest yields. For serious g", Port: 1021, Category: "personal", ProPrice: "$0.99"},
		{Slug: "parcel", Name: "Parcel", Tagline: "Cache npm, PyPI, or Go module downloads locally. Air-gapped environments, faster", Port: 8670, Category: "developer", ProPrice: "$0.99"},
		{Slug: "parcelproxy", Name: "Parcel Proxy", Tagline: "Cache npm, PyPI, or Go module downloads locally. Air-gapped environments, faster", Port: 9700, Category: "developer", ProPrice: "$0.99"},
		{Slug: "parlor", Name: "Parlor", Tagline: "Drop a script tag on your site, your team answers chats from a dashboard. No Int", Port: 9790, Category: "creator", ProPrice: "$0.99"},
		{Slug: "pasture", Name: "Pasture", Tagline: "Write content, schedule it for future publishing, auto-post to configured webhoo", Port: 8730, Category: "creator", ProPrice: "$0.99"},
		{Slug: "pathfinder", Name: "Pathfinder", Tagline: "Define URL rewrite rules, redirects, and proxy mappings via a dashboard instead ", Port: 9740, Category: "developer", ProPrice: "$0.99"},
		{Slug: "pennant", Name: "Pennant", Tagline: "Award points for actions, let users redeem them, track balances. For apps buildi", Port: 1009, Category: "finance", ProPrice: "$0.99"},
		{Slug: "pipeline", Name: "Pipeline", Tagline: "Define data pipelines as DAGs, schedule them, monitor their execution, retry fai", Port: 9140, Category: "developer", ProPrice: "$0.99"},
		{Slug: "plumb", Name: "Plumb", Tagline: "Log every migration run, when it ran, how long it took, whether it succeeded. Kn", Port: 1001, Category: "developer", ProPrice: "$0.99"},
		{Slug: "podium", Name: "Podium", Tagline: "Embed a feedback widget on any page, collect structured responses, tag and prior", Port: 9820, Category: "creator", ProPrice: "$0.99"},
		{Slug: "ponyexpress", Name: "Pony Express", Tagline: "Define email templates, send via your own SMTP or SES account, track opens and c", Port: 8930, Category: "creator", ProPrice: "$0.99"},
		{Slug: "post", Name: "Post", Tagline: "Write posts in Markdown, publish them, set a custom domain. Ghost without the $2", Port: 9999, Category: "creator", ProPrice: "$0.99"},
		{Slug: "prairie", Name: "Prairie", Tagline: "Boards, columns, cards, assignees, due dates. The Trello alternative for teams w", Port: 8820, Category: "operations", ProPrice: "$0.99"},
		{Slug: "presskit", Name: "Presskit", Tagline: "Maintain a public press kit with logos, screenshots, bios, and press coverage li", Port: 9210, Category: "creator", ProPrice: "$0.99"},
		{Slug: "probe", Name: "Probe", Tagline: "Inspect and analyze HTTP requests in real time. See headers, body, timing, and r", Port: 9090, Category: "developer", ProPrice: "$0.99"},
		{Slug: "prospector", Name: "Prospector", Tagline: "Leads, stages, notes, follow-up dates, won/lost tracking. HubSpot CRM is free bu", Port: 9880, Category: "finance", ProPrice: "$0.99"},
		{Slug: "prospector2", Name: "Prospector II", Tagline: "Define scoring rules based on behavior and attributes, score incoming leads auto", Port: 1016, Category: "finance", ProPrice: "$0.99"},
		{Slug: "pulpit", Name: "Pulpit", Tagline: "Build slide decks in Markdown, present from the browser, export to PDF. Reveal.j", Port: 8950, Category: "creator", ProPrice: "$0.99"},
		{Slug: "quarry", Name: "Quarry", Tagline: "Collect logs from any service via syslog or HTTP, index them, search them instan", Port: 9100, Category: "operations", ProPrice: "$0.99"},
		{Slug: "quartermaster", Name: "Quartermaster", Tagline: "Log every item you own — electronics, furniture, appliances — with purchase date", Port: 1023, Category: "personal", ProPrice: "$0.99"},
		{Slug: "quiver", Name: "Quiver", Tagline: "Save articles, books, and courses. Mark progress, take notes, track completion. ", Port: 9910, Category: "personal", ProPrice: "$0.99"},
		{Slug: "rampart", Name: "Rampart", Tagline: "Maintain allow and deny lists, check IPs against known bad actor databases, expo", Port: 1003, Category: "developer", ProPrice: "$0.99"},
		{Slug: "rangeland", Name: "Rangeland", Tagline: "Create isolated workspaces for different teams or clients, each with their own d", Port: 8960, Category: "developer", ProPrice: "$0.99"},
		{Slug: "registry", Name: "Registry", Tagline: "Host your Docker images and private npm/PyPI packages. Pull from your own regist", Port: 9220, Category: "developer", ProPrice: "$0.99"},
		{Slug: "relay", Name: "Relay", Tagline: "Forward incoming webhooks to localhost or internal services during development. ", Port: 8620, Category: "developer", ProPrice: "$0.99"},
		{Slug: "roster", Name: "Roster", Tagline: "Your company org chart, contact list, and team finder — searchable, filterable, ", Port: 8970, Category: "operations", ProPrice: "$0.99"},
		{Slug: "roundup", Name: "Roundup", Tagline: "Create tasks, assign them, track completion, organize by project. The focused Li", Port: 8700, Category: "operations", ProPrice: "$0.99"},
		{Slug: "rustler", Name: "Rustler", Tagline: "Define scraping rules for any URL, schedule runs, store results in structured ta", Port: 8980, Category: "developer", ProPrice: "$0.99"},
		{Slug: "saddlebag", Name: "Saddlebag", Tagline: "Upload, organize, and share files through a clean web interface. Your own intern", Port: 8990, Category: "operations", ProPrice: "$0.99"},
		{Slug: "saloon", Name: "Saloon", Tagline: "Channels, direct messages, file sharing, search. The Slack alternative that does", Port: 8790, Category: "operations", ProPrice: "$0.99"},
		{Slug: "saltlick", Name: "Salt Lick", Tagline: "Manage feature flags, roll out changes gradually, target users by segment. Self-", Port: 9999, Category: "creator", ProPrice: "$0.99"},
		{Slug: "scaffold", Name: "Scaffold", Tagline: "Define project templates, generate new projects from them via API or web UI. You", Port: 9120, Category: "developer", ProPrice: "$0.99"},
		{Slug: "scout", Name: "Scout", Tagline: "Point at a repo or a list of packages, scan for known vulnerabilities, get a rep", Port: 8630, Category: "developer", ProPrice: "$0.99"},
		{Slug: "scribe", Name: "Scribe", Tagline: "Upload audio files, get back transcripts. Run locally with Whisper or connect to", Port: 9270, Category: "creator", ProPrice: "$0.99"},
		{Slug: "seismograph", Name: "Seismograph", Tagline: "Your app POSTs errors, Seismograph deduplicates, groups, and alerts. Self-hosted", Port: 9680, Category: "developer", ProPrice: "$0.99"},
		{Slug: "semaphore", Name: "Semaphore", Tagline: "Set your status (focused, available, out), see your team's status at a glance, ", Port: 9810, Category: "operations", ProPrice: "$0.99"},
		{Slug: "sentinel", Name: "Sentinel", Tagline: "Define alerting rules, route them to email or webhook, suppress duplicates, trac", Port: 8680, Category: "operations", ProPrice: "$0.99"},
		{Slug: "signalman", Name: "Signalman", Tagline: "Define rules against any HTTP data source, fire webhooks when conditions are met", Port: 1002, Category: "operations", ProPrice: "$0.99"},
		{Slug: "silo", Name: "Silo", Tagline: "Define data boundaries between teams, clients, or services. Enforce access rules", Port: 0, Category: "developer", ProPrice: "$0.99"},
		{Slug: "smelter", Name: "Smelter", Tagline: "POST raw data in one format, get it back in another. JSON to CSV, XML to JSON, M", Port: 1004, Category: "developer", ProPrice: "$0.99"},
		{Slug: "soapbox", Name: "Soapbox", Tagline: "Ask questions, answer them, vote, mark as resolved. The knowledge that lives in ", Port: 1010, Category: "operations", ProPrice: "$0.99"},
		{Slug: "spur", Name: "Spur", Tagline: "Define shell tasks, chain them together, schedule them, track their output. The ", Port: 9010, Category: "developer", ProPrice: "$0.99"},
		{Slug: "stampede", Name: "Stampede", Tagline: "Round-robin or weighted traffic across multiple upstream backends. Health checks", Port: 9020, Category: "developer", ProPrice: "$0.99"},
		{Slug: "steward", Name: "Steward", Tagline: "Submit expenses, attach receipts, approve or reject, export to CSV. Expensify ch", Port: 9840, Category: "finance", ProPrice: "$0.99"},
		{Slug: "strongbox", Name: "Strongbox", Tagline: "Store secrets encrypted at rest, share them with teammates by role, rotate them ", Port: 8610, Category: "developer", ProPrice: "$0.99"},
		{Slug: "sundial", Name: "Sundial", Tagline: "Start a timer, tag it to a project or client, stop it, see where your time actua", Port: 9890, Category: "personal", ProPrice: "$0.99"},
		{Slug: "surveyor", Name: "Surveyor", Tagline: "Build forms, embed them anywhere, collect responses, export data. Typeform witho", Port: 9290, Category: "creator", ProPrice: "$0.99"},
		{Slug: "surveyor2", Name: "Surveyor II", Tagline: "Send surveys via email, collect scores, calculate NPS, track trends over time. D", Port: 1013, Category: "creator", ProPrice: "$0.99"},
		{Slug: "switchboard", Name: "Switchboard", Tagline: "Register your services, expose a discovery API, route traffic to healthy instanc", Port: 9170, Category: "developer", ProPrice: "$0.99"},
		{Slug: "switchman", Name: "Switchman", Tagline: "Route production traffic between two versions of a service, shift percentages, m", Port: 9970, Category: "developer", ProPrice: "$0.99"},
		{Slug: "tally", Name: "Tally", Tagline: "Increment counters, set gauges, track arbitrary metrics via HTTP. No SDK require", Port: 8640, Category: "developer", ProPrice: "$0.99"},
		{Slug: "telegraph", Name: "Telegraph", Tagline: "Route notifications from any source to any channel — email, SMS, webhook, Slack.", Port: 9030, Category: "operations", ProPrice: "$0.99"},
		{Slug: "ticker", Name: "Ticker", Tagline: "POST metrics from any service, visualize them in real time, set alert thresholds", Port: 9040, Category: "developer", ProPrice: "$0.99"},
		{Slug: "tinderbox", Name: "Tinderbox", Tagline: "Receive a webhook, run a shell script, report the result. Not Jenkins (Java, hea", Port: 9670, Category: "developer", ProPrice: "$0.99"},
		{Slug: "trailhead", Name: "Trailhead", Tagline: "Define habits, check in daily, visualize streaks and completion rates. Habitica ", Port: 9380, Category: "personal", ProPrice: "$0.99"},
		{Slug: "trough", Name: "Trough", Tagline: "Reverse proxy that logs what each API call costs. Per-route spend breakdown, dai", Port: 9999, Category: "developer", ProPrice: "$0.99"},
		{Slug: "typeset", Name: "Typeset", Tagline: "Point at a directory of Markdown files, get a searchable documentation site. Doc", Port: 9240, Category: "creator", ProPrice: "$0.99"},
		{Slug: "viaduct", Name: "Viaduct", Tagline: "Route /v1/ and /v2/ to different upstream services, deprecate old versions grace", Port: 9660, Category: "developer", ProPrice: "$0.99"},
		{Slug: "watcher", Name: "Watcher", Tagline: "Watch directories for changes, trigger webhooks or shell commands when files are", Port: 8760, Category: "developer", ProPrice: "$0.99"},
		{Slug: "wateringhole", Name: "Watering Hole", Tagline: "Discussion threads, voting, categories, user profiles. Discourse without the $10", Port: 9050, Category: "creator", ProPrice: "$0.99"},
		{Slug: "waystation", Name: "Waystation", Tagline: "Log trips, itineraries, accommodation, expenses. See all your travel history in ", Port: 9930, Category: "personal", ProPrice: "$0.99"},
		{Slug: "windmill", Name: "Windmill", Tagline: "Connect your existing jobs and scripts, visualize their dependencies, see what r", Port: 1018, Category: "developer", ProPrice: "$0.99"},
		{Slug: "wrangler", Name: "Wrangler", Tagline: "Define data pipelines as config, run them on schedule, transform and move data b", Port: 9999, Category: "developer", ProPrice: "$0.99"},
	}
}
